/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    PasswordReset: typeof import('./src/components/PasswordReset.vue')['default']
    PropertyCreator: typeof import('./src/components/PropertyCreator.vue')['default']
    PropertyEditor: typeof import('./src/components/PropertyEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SiteSettings: typeof import('./src/components/SiteSettings.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SuccessMessage: typeof import('./src/components/SuccessMessage.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TransactionCreator: typeof import('./src/components/TransactionCreator.vue')['default']
    TransactionEditor: typeof import('./src/components/TransactionEditor.vue')['default']
    TransactionItem: typeof import('./src/components/TransactionItem.vue')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
  }
}
